### ISSUE TITLE
please add mipsel dependencies to toml

### ISSUE THREAD

**Issue by psych0d0g** [conradkleinespel/rustastic-password#8]
[target.mipsel-unknown-linux-gnu.dependencies]
libc = "0.1"
termios = "0.2"
[target.mips-unknown-linux-gnu.dependencies]
libc = "0.1"
termios = "0.2"

**Comment by conradkleinespel** [comment]
Hello @psych0d0g,

Thanks for taking the time to write this.

Out of curiosity, what is mipsel ?

Best regards

**Comment by psych0d0g** [comment]
mipsel is mostly used for embedded multimedia platforms (enigma2 linux recivers, my LG tv is using it and similar devices)
long endian variant of mips

**Comment by conradkleinespel** [comment]
@psych0d0g: Ah alright, cool ! Thanks for the explanation :smiley:

**Comment by conradkdotcom** [comment]
Hello @psych0d0g !

Had you ever tried actually using this on mipsel ?

The reason I'm asking is that I'm in the process of refactoring this library and I just realised that we had the wrong value of `TCSANOW` in the `termios` crate all this time.

`termios-rs` uses the [Linux default of `0`](https://github.com/dcuddeback/termios-rs/blob/master/src/os/linux.rs#L178) instead of the [actual mips value of `0x540e`](https://github.com/rust-lang/libc/blob/572dc6d914fc07da1875487b3f85f000cfe52562/src/unix/notbsd/linux/mips/mod.rs#L426).
